name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - uses: volta-cli/action@v4.1.1
    - run: node -v
    - run: npm -v
    - run: npm ci
    - run: npm run lint
    - run: npm run sasslint
    - run: npm run test
